### ISSUE TITLE
Illegal operands

### ISSUE THREAD

**Issue by allenderalencar** [ispras/riscv-avs#1]
Hello, i'm trying to run your code: https://github.com/ispras/riscv-avs/tree/master/testsuite/synthetics/rv32v

and getting some illegal operands, when I run: 
riscv64-unknown-elf-gcc -march=rv64gcv -nostdlib -nostartfiles -Trv32v_simple_selfcheck_0000.ld -o rv32v_simple_selfcheck_0000.o rv32v_simple_selfcheck_0000.s

message:
rv32v_simple_selfcheck_0000.s: Assembler messages:
rv32v_simple_selfcheck_0000.s:109: Error: illegal operands `vlw.v v0,t1'
rv32v_simple_selfcheck_0000.s:111: Error: illegal operands `vlw.v v1,t1'
rv32v_simple_selfcheck_0000.s:113: Error: illegal operands `vlw.v v2,t1'
rv32v_simple_selfcheck_0000.s:115: Error: illegal operands `vlw.v v3,t1'
rv32v_simple_selfcheck_0000.s:117: Error: illegal operands `vlw.v v4,t1'
rv32v_simple_selfcheck_0000.s:119: Error: illegal operands `vlw.v v5,t1'
rv32v_simple_selfcheck_0000.s:121: Error: illegal operands `vlw.v v6,t1'
rv32v_simple_selfcheck_0000.s:123: Error: illegal operands `vlw.v v7,t1'
...

Do you know why I`m getting this error and how to solve? thank you for your attention.

**Comment by askamkin** [comment]
Sorry, we uploaded a wrong test. There should be `vlw.v v0, (t1)` and so on. Fixed.

**Comment by allenderalencar** [comment]
working, thank you very much.
